name: Our Artifacts 2
on: push
jobs:
  up:
   runs-on: ubuntu-latest
   steps:
     - run: echo "Holle, Github Actions!" > hello.txt
     - uses: actions/upload-artifact@v4
       with:
         name: hello
         path: hello.txt
  down:
     runs-on: ubuntu-latest
     needs: up #up job에 의존성 up이 완전히 끝나야 down 실행 
     steps:
       - run: cat hello.txt
         continue-on-error: true
       - uses: actions/download-artifact@v4
         with:
           name: hello
       - run: cat hello.txt
